PinNote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('notes/', include('notes.urls')),
    path('profile/', include('profiles.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('informations/', views.InformationsView.as_view(), name='informations'),
    path('devInformations/', views.DevInformationsView.as_view(), name='devInformations'),
]

notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.NotesView.as_view(), name='notes'),
    path('create/', views.CreateNoteView.as_view(), name='create'),
    path('delete/', views.DeleteView.as_view(), name='delete'),
    path('update/', views.UpdateView.as_view(), name='update'),
    path('<slug>/', views.NoteDetailsView.as_view(), name='details'),
]

profiles/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    path('', views.SignInView.as_view(), name='signin'),
    path('login/', views.LogInView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('update/', views.UpdateView.as_view(), name='update'),
]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ValidationError

from utils.validacpf import valida_cpf

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='User')
    date = models.DateField('Nascimento', )
    cpf = models.CharField('cpf', max_length=11)
    country = models.CharField(
        max_length=2,
        default='DT',
        choices=(
            ('DT', 'Default'),
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )

    def __str__(self):
        return f'{self.user}/{self.date}/{self.cpf}/{self.country}'

    def clean(self):
        error_messages = {}

        if not valida_cpf(self.cpf):
            error_messages['cpf'] = 'Digite um CPF válido!'

        if self.country == 'DT':
            error_messages['country'] = 'Selecione um estado válido!'

        if error_messages:
            raise ValidationError(error_messages)

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

profiles/forms.py
from django import forms 
from django.contrib.auth.models import User

from . import models

class UserFormCreate(forms.ModelForm):
    first_name = forms.CharField(
        label= 'Primeiro nome',
        help_text= 'Digite seu primeiro nome. Ex: João'
    )

    last_name = forms.CharField(
        label= 'Sobrenome',
        help_text= 'Digite seu sobrenome. Ex: Pereira Silva'
    )

    username = forms.CharField(
        help_text= 'DIgite seu nome de usuário. Ex: TheDoctor'
    )

    email = forms.EmailField(
        label= 'E-mail',
        help_text= 'Digite seu e-mail aqui. Ex: exemploEmail@email.com'
    )

    password = forms.CharField(
        label= 'Senha',
        widget=forms.PasswordInput(),
    )

    password_2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Confirmação de senha'
    )

    def __int__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'password_2', 'email',)

    def clean(self, *args, **kwargs):
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        user_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password_data_2 = cleaned.get('password_2')

        user_db = User.objects.filter(username=user_data).first()
        email_db = User.objects.filter(email=email_data).first()

        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'E-mail já existe'
        error_msg_password_match = 'As senhas não conferem'
        error_msg_password_shot = 'Sua senha precisa de pelo menos 6 caracteres'
        error_msg_required_field = 'Este campo é obrigatório!'

        if user_db:
            validation_error_msgs['username'] = error_msg_user_exists

        if email_db:
            validation_error_msgs['email'] = error_msg_email_exists

        if not password_data:
            validation_error_msgs['password'] = error_msg_required_field

        if not password_data_2:
            validation_error_msgs['password_2'] = error_msg_required_field

        if password_data:
            if password_data != password_data_2:
                    validation_error_msgs['password'] = error_msg_password_match
                    validation_error_msgs['password_2'] = error_msg_password_match
                    
            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_shot

        if validation_error_msgs:
            raise(forms.ValidationError(validation_error_msgs))

class ProfileForm(forms.ModelForm):
    date = forms.DateField(
        label= 'Nascimento',
        help_text= 'Formato da data YYYY-MM-DD'
    )

    cpf = forms.CharField(
        help_text= 'Colocar CPF sem pontuação'
    )

    country = forms.ChoiceField(
        label= 'Estado',
        help_text= 'Selecione seu estado',
        choices=(
            ('DT', 'Default'),
            ('AC', 'Acre'),
            ('AL', 'Alagoas'),
            ('AP', 'Amapá'),
            ('AM', 'Amazonas'),
            ('BA', 'Bahia'),
            ('CE', 'Ceará'),
            ('DF', 'Distrito Federal'),
            ('ES', 'Espírito Santo'),
            ('GO', 'Goiás'),
            ('MA', 'Maranhão'),
            ('MT', 'Mato Grosso'),
            ('MS', 'Mato Grosso do Sul'),
            ('MG', 'Minas Gerais'),
            ('PA', 'Pará'),
            ('PB', 'Paraíba'),
            ('PR', 'Paraná'),
            ('PE', 'Pernambuco'),
            ('PI', 'Piauí'),
            ('RJ', 'Rio de Janeiro'),
            ('RN', 'Rio Grande do Norte'),
            ('RS', 'Rio Grande do Sul'),
            ('RO', 'Rondônia'),
            ('RR', 'Roraima'),
            ('SC', 'Santa Catarina'),
            ('SP', 'São Paulo'),
            ('SE', 'Sergipe'),
            ('TO', 'Tocantins'),
        )
    )

    class Meta:
        model = models.Profile
        fields = ('date', 'cpf', 'country')
        exclude = ('user',)


class UserFormUpdate(forms.ModelForm):
    first_name = forms.CharField(
        label= 'Primeiro nome',
        help_text= 'Digite seu primeiro nome. Ex: João'
    )

    last_name = forms.CharField(
        label= 'Sobrenome',
        help_text= 'Digite seu sobrenome. Ex: Pereira Silva'
    )

    username = forms.CharField(
        help_text= 'DIgite seu nome de usuário. Ex: TheDoctor'
    )

    email = forms.EmailField(
        label= 'E-mail',
        help_text= 'Digite seu e-mail aqui. Ex: exemploEmail@email.com'
    )

    password = forms.CharField(
        label= 'Senha',
        required=False, 
        widget=forms.PasswordInput(),
    )

    password_2 = forms.CharField(
        label= 'Confirmação de senha',
        required=False,
        widget=forms.PasswordInput(),
    )

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.user = user

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'password_2', 'email',)

    def clean(self, *args, **kwargs):
        cleaned = self.cleaned_data
        validation_error_msgs = {}

        username_data = cleaned.get('username')
        email_data = cleaned.get('email')
        password_data = cleaned.get('password')
        password_data_2 = cleaned.get('password_2')

        user_db = User.objects.filter(username=username_data).first()

        error_msg_user_exists = 'Usuário já existe'
        error_msg_email_exists = 'E-mail já existe'
        error_msg_password_match = 'As senhas não conferem'
        error_msg_password_shot = 'Sua senha precisa de pelo menos 6 caracteres'

        if username_data != user_db.username:
            if user_db:
                validation_error_msgs['username'] = error_msg_user_exists

        if email_data != user_db.email:
            if user_db.email:
                validation_error_msgs['email'] = error_msg_email_exists

        if password_data:
            if password_data != password_data_2:
                validation_error_msgs['password'] = error_msg_password_match
                validation_error_msgs['password_2'] = error_msg_password_match
                    
            if len(password_data) < 6:
                validation_error_msgs['password'] = error_msg_password_shot

profiles/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views import View
from django.contrib import messages
from django import forms

from . import forms
from . import models

class SignInView(View):
    template_name = 'profile/signin.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.profile = None

        self.context = {
            'userForm': forms.UserFormCreate(data=self.request.POST or None),
            'profile': forms.ProfileForm(data=self.request.POST or None),
        }

        self.userForm = self.context['userForm']
        self.profile = self.context['profile']

        self.render = render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if not self.userForm.is_valid() or not self.profile.is_valid():
            return self.render

        password = self.userForm.cleaned_data.get('password')
        
        user = self.userForm.save(commit=False)
        user.set_password(password)
        user.save()

        profile = self.profile.save(commit=False)
        profile.user = user
        profile.save()
        
        if password:
            authenticates = authenticate(
                self.request,
                username=user,
                password=password,
            )

            if authenticates:
                login(self.request, user=user)

                return redirect('home:index')

        return self.render
    
    def get(self, *args, **kwargs):
        return self.render

class LogoutView(View):
    def get(self, *args, **kwargs):
        logout(self.request)
        
        return redirect('home:index')

class LogInView(View):
    template_name = 'profile/login.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name)

    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')

        if not username or not password:
            messages.error(
                self.request,
                'Usuário ou senha inválidos!'
            )
            return redirect('profile:login')

        user = authenticate(self.request, username=username, password=password)

        if not user:
            messages.error(
                self.request,
                'Usuário ou senha inválidos!'
            )
            return redirect('profile:login')

        login(self.request, user=user)

        return redirect('home:index')
        

class UpdateView(View):
    template_name = 'profile/update.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        
        self.profile = models.Profile.objects.filter(user=self.request.user).first()
        
        self.context = {
            'userForm': forms.UserFormUpdate(data=self.request.POST or None, user=self.request.user, instance=self.request.user),
            'profileForm': forms.ProfileForm(data=self.request.POST or None, instance=self.profile),
        }

        self.userForm = self.context['userForm']
        self.profileForm = self.context['profileForm']

        self.render = render(self.request, self.template_name, self.context)


    def post(self, *args, **kwargs):
        if not self.userForm.is_valid() or not self.profileForm.is_valid():
            return self.render
        else:
            username = self.userForm.cleaned_data.get('username')
            password = self.userForm.cleaned_data.get('password')
            email = self.userForm.cleaned_data.get('email')
            first_name = self.userForm.cleaned_data.get('first_name')
            last_name = self.userForm.cleaned_data.get('last_name')

            date = self.profileForm.cleaned_data.get('date')
            cpf = self.profileForm.cleaned_data.get('cpf')
            country = self.profileForm.cleaned_data.get('country')

            if self.request.user.is_authenticated:
                user = get_object_or_404(User, username=self.request.user.username)

                user.username = username

                if password:
                    user.set_password(password)

                user.email = email

                user.first_name = first_name
                user.last_name = last_name
                user.save()

                profile = models.Profile.objects.all().filter(user=user)
                profile.date = date
                profile.cpf = cpf
                profile.country = country
                self.profile.save()

            return redirect('profile:update')
    
    def get(self, *args, **kwargs):
        return self.render

profiles/templates/partials/_footer.html
{% load static %}

<footer class="lilac-foot mt-5">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Ernesto Santos</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'font-awesome/js/all.js' %}"></script>

profiles/templates/partials/_head.html
{% load static %}
    
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/index.css' %}">

profiles/templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

profiles/templates/partials/_nav.html
<nav class="navbar navbar-dark navbar-expand-lg lilac">
    <a class="navbar-brand royal" href="{% url 'home:index' %}">Pin Note</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:informations' %}">Informações do projeto</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:devInformations' %}">Informações do desenvolvedor</a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link royal" href="{% url 'notes:notes' %}">Notas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'notes:create' %}">Criar nota</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Informações de conta
                    </a>
                    <div class="dropdown-menu nav-item" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'profile:update' %}">Atualizar dados</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'profile:logout' %}">Log out</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile:signin' %}">Criar uma conta</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile:login' %}">Fazer login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

profiles/templates/partials/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}