PinNote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('notes/', include('notes.urls')),
    path('profile/', include('profiles.urls')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('informations/', views.InformationsView.as_view(), name='informations'),
    path('devInformations/', views.DevInformationsView.as_view(), name='devInformations'),
]

notes/urls.py
from django.urls import path

from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.NotesView.as_view(), name='notes'),
    path('create/', views.CreateNoteView.as_view(), name='create'),
    path('delete/', views.DeleteView.as_view(), name='delete'),
    path('update/', views.UpdateView.as_view(), name='update'),
    path('<slug>/', views.NoteDetailsView.as_view(), name='details'),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User')
    noteName = models.CharField('Título', max_length=50)
    createDate = models.DateTimeField(default=timezone.now)
    description = models.CharField('Descrição', max_length=50)
    noteInformation = models.TextField('Informações da nota')
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.user)}_{slugify(self.noteName)}'
            self.slug = slug

        super().save(*args,**kwargs)

    def __str__(self):
        return self.noteName

    class Meta:
        verbose_name = "Note"
        verbose_name_plural = "Notes"

notes/forms.py
from django import forms

from . import models

class NoteForm(forms.ModelForm):

    class Meta:
        model = models.Notes
        fields = ('noteName', 'description', 'noteInformation')
        exclude = ('user', 'createDate', 'slug')

notes/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User

from . import models

from . import forms

class NotesView(View):
    template_name = 'notes/homeNotes.html'
    paginate_by = 10

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        user = self.request.user

        notes = models.Notes.objects.all().filter(user=user)

        self.context = {
            'notes': notes,
        }

        self.render = render(self.request, self.template_name, self.context)

    def get(self, *args, **kwargs):
        return self.render

class CreateNoteView(View):
    template_name = 'notes/createNote.html'
    
    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        
        self.context = {
            'createNoteForm': forms.NoteForm(data=self.request.POST or None),
        }

        self.noteForm = self.context['createNoteForm']

        self.render = render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if not self.noteForm.is_valid():
            return self.render
        else:
            if self.request.user.is_authenticated:
                note = self.noteForm.save(commit=False)
                note.user = self.request.user
                note.save()
                return redirect('notes:create')
            else:
                return redirect('profile:login')

    def get(self, *args, **kwargs):
        return self.render


class DeleteView(View):
    def get(self, *args, **kwargs):
        variation_id = self.request.GET.get('vid')
        
        if not variation_id:
            return redirect('notes:notes')

        notes = models.Notes.objects.filter(id=variation_id).delete()
        self.request.session.save()
        return redirect('notes:notes')

class UpdateView(View):
    template_name = 'notes/update.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.id_note = self.request.GET.get('vid')

        self.note = models.Notes.objects.filter(id=self.id_note).first()

        self.context = {
            'updateNote':forms.NoteForm(data=self.request.POST or None, instance=self.note),
        }

        self.noteForm = self.context['updateNote']

        self.render = render(self.request, self.template_name, self.context)

    def post(self, *args, **kwargs):
        if not self.noteForm.is_valid():
            return self.render
        else:
            noteName = self.noteForm.cleaned_data.get('noteName')
            description = self.noteForm.cleaned_data.get('description')
            noteInformation = self.noteForm.cleaned_data.get('noteInformation')

            if self.request.user.is_authenticated:
                user = get_object_or_404(User, username=self.request.user.username)

                note = models.Notes.objects.all().filter(id=self.id_note)
                note.noteName = noteName
                note.description = description
                note.noteInformation = noteInformation
                self.note.save()

        return redirect('notes:notes')

    def get(self, *args, **kwargs):
        return self.render

class NoteDetailsView(DetailView):
    model = models.Notes
    template_name = 'notes/details.html'
    context_object_name = 'notes'
    slug_url_kwarg = 'slug'

notes/templates/notes/createNote.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ createNoteForm|crispy }}
    <button type="submit" class="btn btn-brown text-light mb-1">Salvar</button>
</form>
    
{% endblock %}

notes/templates/notes/details.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div class="col-lg">
        <div class="text-center mt-lg mt-4 mb-4">
            <h1>{{ notes.noteName }}</h1>
        </div>
        <br>
        <div class="card text-center mt-lg mb-4">
            <h3 class="mt-2">Data de criação:</h3>
            <p class="text-justify pl-3 pr-3">{{ notes.createDate }}</p>
        </div>
        <br>
        <div class="card text-center mt-lg mb-4">
            <h3 class="mt-2">Descrição da tarefa: </h3>
            <p class="text-justify pl-3 pr-3">{{ notes.description }}</p>
        </div>
        <br>
        <div class="card text-center mt-lg mb-5">
            <h3 class="mt-2">Informações extras para a tarefa:</h3>
            <p class="text-justify pl-3 pr-3">{{ notes.noteInformation }}</p>
        </div>
    </div>
</div>
{% endblock %}

notes/templates/notes/homeNotes.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mt-5 mb-4">Lista de tarefas</h1>
    <div class="list-group mb-5">
    {% if notes %}
    {% for note in notes %}
        <div class="list-group-item">
            <a class="ml-3" href="{% url 'notes:update' %}?vid={{ note.id }}">
                <i class="fas fa-wrench"></i>
            </a>
            <a class="ml-3" href="{% url 'notes:delete' %}?vid={{ note.id }}">
                <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
            </a>
            <a href="{{ note.slug }}" class="text-dark col-md col-8">{{ note.noteName }}</a>
        </div>
    {% endfor %}
    {% else %}
        <div class="container text-center">
            <h3>Você precisa adicionar notas para que elas apareçam aqui!</h3>
            <br>
            <h3>&#128525</h3>
        </div>
    </div>
    {% endif %}
{% endblock %}

notes/templates/notes/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ updateNote|crispy }}
    <button type="submit" class="btn btn-brown text-light mb-1">Salvar</button>
</form>
{% endblock %}